### ISSUE TITLE
In Jenkins build Report and Analyze Results link don't open actual Checkmarx link

### ISSUE THREAD

**Issue by natrajms** [jenkinsci/checkmarx-ast-scanner-plugin#133]
### What feature do you want to see added?

Both link points to below URL. It has extra **CxWebClient**
https://_<Checkmarx_URL>_/**CxWebClient**/CxWebClient/ViewerMain.aspx?scanId=_INTEGER_&ProjectID=_INTEGER_

**Comment by natrajms** [comment]
![image](https://user-images.githubusercontent.com/111265283/213868047-1b1448f5-ffdc-4f5a-b543-af2dafdda56e.png)
When we click Checkmarx Results link in Jenkins job it opens URL 

https://<DOMAIN.COM>/**CxWebClient/CxWebClient**/ViewerMain.aspx?scanId=2222222&ProjectID=1111111

Here CxWebClient is added twice in URL. Hence correct URL is not loaded.

**Comment by pedrompflopes** [comment]
Hi @natrajms  

This plugin is for checkmarx One, it seems you are using the checkmarx SAST plugin. 
https://github.com/jenkinsci/checkmarx-plugin 

Can you please open a ticket there or create a salesforce ticket ? 

Thanks!
